products = [
    {'type': "milk", 'department': "Молоко", 'name': "Молоко ультрапастеризованное", 'measurement': "литр"},
    {'type': "eco", 'department': "Молоко", 'name': "Молоко безлактозное", 'measurement': "литр"},
    {'type': "milk", 'department': "Молоко", 'name': "Молоко детское с 8 месяцев", 'measurement': "литр"},
    {'type': "milk", 'department': "Молоко", 'name': "Кефир 3,2%", 'measurement': "литр"},
    {'type': "milk", 'department': "Молоко", 'name': "Кефир обезжиренный", 'measurement': "литр"},
    {'type': "milk", 'department': "Молоко", 'name': "Ряженка термостатная", 'measurement': "литр"},
    {'type': "milk", 'department': "Молоко", 'name': "Сливки 10%", 'measurement': "литр"},
    {'type': "milk", 'department': "Молоко", 'name': "Сливки 35% для взбивания", 'measurement': "литр"},
    {'type': "milk", 'department': "Молоко", 'name': "Сметана 15%", 'measurement': "литр"},
    {'type': "milk", 'department': "Молоко", 'name': "Сметана 25%", 'measurement': "литр"},
    {'type': "eco", 'department': "Молоко", 'name': "Молоко кокосовое", 'measurement': "литр"},
    {'type': "eco", 'department': "Молоко", 'name': "Молоко овсяное", 'measurement': "литр"},
    {'type': "milk", 'department': "Молоко", 'name': "Творог 9% жирности", 'measurement': "кг"},
    {'type': "milk", 'department': "Молоко", 'name': "Творожок детский сладкий", 'measurement': "кг"},
    {'type': "eggs", 'department': "Молоко", 'name': "Яйцо диетическое", 'measurement': "шт"},
    {'type': "milk", 'department': "Молоко", 'name': "Масло сливочное крестьянское", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Крупа гречневая ядрица", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Крупа манная", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Крупа пшено", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Крупа перловая", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Рис круглозерный", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Рис длиннозерный", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Бурый рис", 'measurement': "кг"},
    {'type': "pasta", 'department': "Бакалея", 'name': "Макароны спагетти ", 'measurement': "кг"},
    {'type': "pasta", 'department': "Бакалея", 'name': "Макароны вермишель", 'measurement': "кг"},
    {'type': "pasta", 'department': "Бакалея", 'name': "Макароны рожки", 'measurement': "кг"},
    {'type': "pasta", 'department': "Бакалея", 'name': "Макароны перья", 'measurement': "кг"},
    {'type': "tea-coffe", 'department': "Бакалея", 'name': "Сахар песок белый", 'measurement': "кг"},
    {'type': "tea-coffe", 'department': "Бакалея", 'name': "Сахар демерара коричневый", 'measurement': "кг"},
    {'type': "tea-coffe", 'department': "Бакалея", 'name': "Сахар рафинад быстрорастворимый", 'measurement': "кг"},
    {'type': "eco", 'department': "Бакалея", 'name': "Лапша гречневая", 'measurement': "кг"},
    {'type': "eco", 'department': "Бакалея", 'name': "Фунчоза", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Мука хлебопекарная в\с", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Мука блинная", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Горох желтый колотый", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Чечевица красная", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Хлопья овсяные Геркулес", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Хлопья 4 злака", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Кукурузные хлопья с сахаром", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Соль каменная помол №1", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Соль поваренная Экстра", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Крахмал картофельный", 'measurement': "кг"},
    {'type': "grain", 'department': "Бакалея", 'name': "Сода пищевая", 'measurement': "кг"},
    {'type': "tea-coffe", 'department': "Бакалея", 'name': "Чай черный индийский", 'measurement': "кг"},
    {'type': "tea-coffe", 'department': "Бакалея", 'name': "Чай зеленый ", 'measurement': "кг"},
    {'type': "tea-coffe", 'department': "Бакалея", 'name': "Кофе растворимый", 'measurement': "кг"},
    {'type': "tea-coffe", 'department': "Бакалея", 'name': "Кофе в зернах ", 'measurement': "кг"},
    {'type': "tea-coffe", 'department': "Бакалея", 'name': "Кофе молотый", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Колбаса вареная докторская", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Колбаса вареная любительская", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Сервелат варенокопченый", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Колбаса краковская", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Сосиски молочные", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Сосиски венские", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Сосиски куриные", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Сардельки", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Колбаса сырокопченая салями", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Бекон варенокопченый", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Бекон сырокопченый", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Грудинка копченая", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Ветчина в оболочке", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Паштет фермерский с грибами", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Паштет из куриной печени", 'measurement': "кг"},
    {'type': "meat", 'department': "Мясная гастрономия", 'name': "Колбаса ливерная", 'measurement': "кг"}
]